### ISSUE TITLE
Web UI Blank/Not Loading

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#12]
Hey there- I'm seeing the following error when I attempt to browse to the Web UI. Same error across browsers (Firefox and Chromium)

Current Node version: v14.17.3 (updated today - I'm betting this is the culprit)
Current NPM version: 8.5.5

```
Mar 23 09:04:16 mlbserver[69436]: 3/23/2022, 9:04:16 AM getDayData error : getObj is not defined
Mar 23 09:04:16 mlbserver[69436]: 3/23/2022, 9:04:16 AM home request error : Cannot read property 'dates' of undefined
```

**Comment by ahughes03** [comment]
Changed to Node version 16.14.2 and I'm still seeing the error, so Node might not be the culprit after all...

**Comment by tonywagner** [comment]
Still works for me... I had been using Node 14.8.0, but I just tried it on a fresh Mac system with Node 17.8.0 / NPM 8.5.5 from [here](https://nodejs.org/en/download/current/) and it worked fine too (5 warnings during the installation about deprecated packages, but it installed and ran without a problem).

Looks like "getObj" was an old typo in the code, only triggered if certain functions like getDayData didn't return valid JSON. I just fixed that, if you want to try again with the "--debug" switch to see what's going on.

**Comment by ahughes03** [comment]
Thanks- so I went to reload the web-ui, and it's working now (version 2022.03.22), without me having done anything since I opened the issue. So I guess the query didn't return a valid JSON for whatever reason when I went to look at the schedule this morning.

Thanks for the quick reply and patch, I'll update and close the issue as long as things come back up correctly.

**Comment by tonywagner** [comment]
Glad to hear it! May have just been a fluke.

**Comment by ahughes03** [comment]
Closing this issue, but a new one incoming due to the update to 2022.03.23
