### ISSUE TITLE
Similar problem to closed #11

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#14]
Hey there, I'm seeing a few instances where the mlbserver XML isn't providing links back to available feeds.

For instance:

```
8/31/2022, 2:07:04 PM stream.m3u8 request : /stream.m3u8?team=SD&mediaType=Video&resolution=720p60 from: ::ffff:10.0.0.11 using: xTeVe
8/31/2022, 2:07:04 PM could not find mediaId
8/31/2022, 2:07:04 PM no matching game found /stream.m3u8?team=SD&mediaType=Video&resolution=720p60
8/31/2022, 2:07:04 PM failed to get mediaId : /stream.m3u8?team=SD&mediaType=Video&resolution=720p60
```

But if I pull the stream directly from the mlbserver ui:

```
8/31/2022, 2:10:55 PM embed.html request : /embed.html?mediaId=d340db8c-c68e-4ae3-ab7b-a8c05c9e86cc&startFrom=Live&resolution=720p60 from: ::ffff:10.0.0.13 using: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
8/31/2022, 2:10:55 PM stream.m3u8 request : /stream.m3u8?mediaId=d340db8c-c68e-4ae3-ab7b-a8c05c9e86cc&startFrom=Live&resolution=720p60 from: ::ffff:10.0.0.13 using: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
```

I've tried deleting a re-adding the mlbserver m3u and xml to xTeVe, but it's giving me the same issues. Interestingly enough, xTeVe can pull the opposing team feed without issue...

Thanks in advance for looking at it- not sure if there's any other factors to consider...

**Comment by tonywagner** [comment]
When I refactored getMediaId recently, I apparently neglected to include away team streams!

Should be fixed now with https://github.com/tonywagner/mlbserver/commit/74cc35038685adb937a88c350ba427795aa21744

**Comment by ahughes03** [comment]
Awesome, I've updated and tested with an away team, all is working.
