### ISSUE TITLE
Access Token Parse failure

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#16]
I'm getting the following error when trying to view games.

```
3/7/2023, 2:45:14 PM retrieveOktaAccessToken parse failure
http get failed : 401 - ""
{
  url: 'https://media-entitlement.mlb.com/api/v3/jwt',
  headers: {
    Authorization: 'Bearer undefined',
    Origin: 'https://www.mlb.com',
```

The one other line I'm seeing that may be relevant says: `PM invalid cookie storage file contents, resetting` but I'm not sure if that's the issue. Any idea if the `Bearer undefined` log entry is causing the issue?

**Comment by ahughes03** [comment]
Looks like this was tackled in Issue #15.. I'm thinking the docker image is still pending update since my mlbserver instance (in a docker container) is still on 2022.10.07

**Comment by tonywagner** [comment]
Correct. I just pushed the update to Docker now. Enjoy!
