### ISSUE TITLE
2023-03-04 getTVData error

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#17]
Thanks for the Docker update. Unfortunately Jellyfin is throwing the following error when trying to use the m3u/xml links directly from mlbserver. Any ideas? This issue wasn't present before the 2022-03-04 update. It seems like neither Jellyfin or xTeVe can parse the m3u/xml data. Here's the only log line that pops up.

```
PM getTVData error : Cannot read properties of undefined (reading '2023-03-07')
```

xTeVe gives the following lines:

```
[xTeVe] [ERROR] Invalid M3U file, an extended M3U file is required. () - EC: 0
[ERROR] EOF () - EC: 0
```
Jellyfin doesn't give any relevant logging.

**Comment by tonywagner** [comment]
What's the M3U URL you are using?

**Comment by ahughes03** [comment]
I've tried a few. They're all iterations of my LAN address...

Here are my two main ones

`http://10.0.0.11:9999/channels.m3u?mediaType=Video&resolution=720p60`
`http://10.0.0.11:9999/channels.m3u?mediaType=Video&excludeTeams=multiview`

**Comment by ahughes03** [comment]
It seems like most of the m3u links that mlbserver is offering are linking to blank files with 0 bytes of data. The one that does work is the link for gamechanger:

`http://10.0.0.11:9999/channels.m3u?mediaType=Video&resolution=720p60&includeTeams=gamechanger`

I adapted it to `http://10.0.0.11:9999/channels.m3u?mediaType=Video&resolution=720p60&includeTeams=SD` and that allows both Jellyfin and xTeVe to gain access to the programming.  

Removing the `&includeTeams` brings us back to the same error- a 0 byte m3u file that has zero data.

I hope that helps?

**Comment by ahughes03** [comment]
That fixed it immediately. Thanks!

**Comment by tonywagner** [comment]
I just pushed a new version that disables Big Inning schedule scraping (will just generate a generic schedule for now). Also added more debug code when generating M3U/XML data.
