### ISSUE TITLE
Add favorite team example to readme 

### ISSUE THREAD

**Issue by akatreyt** [tonywagner/mlbserver#18]
Currently there is no documentation on format for adding a favorite team. Hou, Astros, teamid, etc … would be great if there was an example.

**Comment by tonywagner** [comment]
Will do. Documentation is intentionally kind of sparse, but I could add the team abbreviations, and maybe even a way to specify favorites in the web interface.

**Comment by tonywagner** [comment]
Addressed a bit in https://github.com/tonywagner/mlbserver/commit/93a553c91113949c63b2cc51b3be259a064ad348

I am also sketching out an overhaul of mlbserver that will also include being able to set favorite teams from the web interface.
