### ISSUE TITLE
Request: add simple html auth to page 

### ISSUE THREAD

**Issue by akatreyt** [tonywagner/mlbserver#19]
Would love to be able to out this behind a remote proxy for viewing while away from home network. If there was a way to setup basic auth and set the user name and pass in the env that would be amazing.

**Comment by tonywagner** [comment]
Already there! See “page_username” and “page_password” in the readme.

Once you specify those, the server also generates a random “content_protect” string. You can add that to any mlbserver URL to bypass the login prompt, which is handy for bookmarking or using certain media players.
