### ISSUE TITLE
NHL?

### ISSUE THREAD

**Issue by schwyl** [tonywagner/mlbserver#21]
Is there a possibility this could be reconfigured to use Sportsnet Now feeds andNHL.TV feeds?

**Comment by tonywagner** [comment]
I suspect it could be adapted for NHL.TV, but it would need to be done by a non-US user since NHL.TV is not available in the US anymore.

Same for Sportsnet Now.

**Comment by schwyl** [comment]
Im in canada, but not a programmer. Is there anyway you could help me make
it work for sportsnet now?

**Comment by schwyl** [comment]
Yeah I was pretty disappointed when Rogers took everything over. RIght now
I just fire up 4 chrome sessions use the multi view on the web then cast
the desktop.

I will say that your program is awesome for base ball. Is there any way you
could add the functionality to have more that 1 set of multiview going.

IE:  Multiview - 1,2,3,4 Multiview 5,6,7,8

CUrrently I built 3 docker images and run them like that

**Comment by tonywagner** [comment]
Great minds think alike! Multiple multiview streams is in the planning stages.

[Private message me on Reddit](https://www.reddit.com/message/compose/) and I could potentially look into the NHL/Sportsnet stuff at some point.
