### ISSUE TITLE
Last update seems to have broken predictive links

### ISSUE THREAD

**Issue by charliebird** [tonywagner/mlbserver#22]
First off, thanks a lot for adding the Skip Commercials option, that's exactly what I wanted.
But since I've installed the update, my predictive links aren't working anymore
ex:
http://*mlbserverIP*/stream.m3u8?team=NYM&resolution=720p60&skip=pitches&date=yesterday 

returns the default content instead of the MLB stream

**Comment by tonywagner** [comment]
That link works fine for me. You may have to toggle “scan mode” off, on the home page.

**Comment by charliebird** [comment]
Ok that did the trick. Thanks!
