### ISSUE TITLE
Change Server IP

### ISSUE THREAD

**Issue by SkinnyVans** [tonywagner/mlbserver#23]
First off, this is amazing so thank you.

I am wondering if there is a way to change the mlbserver IP or select it to run from a different network interface?

**Comment by tonywagner** [comment]
I think it should just bind to all of the available interfaces, and be available on all of that machine's IPs.

If you want to only bind to a specific IP, you can do that with Docker:
[Docker Container networking: Published ports](https://docs.docker.com/config/containers/container-networking/#published-ports)

You can also tell a Docker container to use the network provided by another Docker container. For example, adding this to your mlbserver Docker run command would tell it to use the network provided by the "mywifi" container:
`--net=container:mywifi`
