### ISSUE TITLE
Team URL argument not accurate?

### ISSUE THREAD

**Issue by cr08** [tonywagner/mlbserver#24]
One of the primary intents of this application on my own system is to have a dedicated and consistent stream url I can add to something like VLC for a single minor league team and leave it. I've set the fav_teams variable but in practice it is hit or miss some days if the right team shows or if it is a different team (often with the same abbreviation which may have something to do with it?)

The team in question is the Columbus Clippers (COL) under the Cleveland franchise (CLE). 'COL' is set in fav_teams and in the example links the team video stream link gives me this which seems right:

`http://192.168.1.X:9898/stream.m3u8?team=COL&resolution=best`

There are cases where I'll get like Colorado for example instead.

Any ideas how I can accomplish this?

**Comment by tonywagner** [comment]
Good catch! I had assumed all the team abbreviations were unique -- and many of them are -- but apparently there are at least three different teams using the "COL" abbreviation (Colorado, Columbus, and Columbia). It was probably just returning the first one it found among those 3 teams.

So I just added a "level" URL parameter for stream.m3u8 in the latest commit: https://github.com/tonywagner/mlbserver/commit/51258265bfd86d6a84a7e16dae242b911a1519ed

To get Columbus games, you'd now specify "?team=COL&level=AAA" in your stream link; "?team=COL&level=AA" would get you Columbia (Royals AA affiliate). Omitting the level parameter implies MLB which would give you Colorado.
