### ISSUE TITLE
Issues pulling feed via XML/m3u again

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#28]
Hey there, happy Spring Training...

Here are my logs. Pulling the stream directly in the mlbserver gui poses no issue, it's only when I try to pull a Dodgers stream via the m3u. 

The first two lines are directly from the web ui, and it works without any issues. The second group of entries is when I try to watch a Dodgers game via the m3u8 feed. There's a parameter `level=undefined` that I think might be throwing the issue. The last two lines are when I watch an Angels game via the m3u8 feed. The `level` parameter is not included in the stream request, and the game is playing just fine.

```
3/2/2024, 1:37:57 PM embed.html request : /embed.html?mediaId=XXX&startFrom=Live&resolution=720p60&audio_track=English from: ::ffff:10.0.0.15 using: Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0
3/2/2024, 1:37:57 PM stream.m3u8 request : /stream.m3u8?mediaId=XXX&startFrom=Live&resolution=720p60&audio_track=English from: ::ffff:10.0.0.15 using: Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

3/2/2024, 1:38:14 PM stream.m3u8 request : /stream.m3u8?team=LAD&mediaType=Video&level=undefined&resolution=720p60 from: ::ffff:172.18.0.1 using: Jellyfin-Server/10.8.13
3/2/2024, 1:38:14 PM could not find mediaId or gamePk
3/2/2024, 1:38:14 PM no matching game found /stream.m3u8?team=LAD&mediaType=Video&level=undefined&resolution=720p60
3/2/2024, 1:38:14 PM failed to get mediaId : /stream.m3u8?team=LAD&mediaType=Video&level=undefined&resolution=720p60

3/2/2024, 1:39:30 PM stream.m3u8 request : /stream.m3u8?team=LAA&mediaType=Video&resolution=720p60 from: ::ffff:172.18.0.1 using: Jellyfin-Server/10.8.13
3/2/2024, 1:39:40 PM stream.m3u8 request : /stream.m3u8?team=LAA&mediaType=Video&resolution=720p60 from: ::ffff:172.18.0.1 using: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36
```
Any ideas? As far as I can tell, this is only happening with Dodger games, I haven't had the issue pop up with other feeds so far this Spring.

**Comment by tonywagner** [comment]
Appears to have been a bug exposed by the upcoming South Korea games. Fixed in https://github.com/tonywagner/mlbserver/commit/3b6ad1450bfb259608968cfa48159d42d817952f, let me know if you run into any other trouble.

**Comment by ahughes03** [comment]
Will do- looks like the next Dodger game will be on 3/5- I'll come back if there's still an issue!
