### ISSUE TITLE
getMediaId error : Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#3]
Hey there, I started to get this error in my log when attempting to connect to a stream via xTeVe. I'm able to play streams directly from the npm app, but when I plug in all the pertinent data to xTeVe, I'm getting the error in the subject-line. This is a new error...
```
stream.m3u8 request : /stream.m3u8?team=XXXXX
getMediaId error : Cannot read property 'content' of undefined
failed to get mediaId : /stream.m3u8?team=XX&mediaType=Video&resolution=720p_alt
failed to get streamURL : /stream.m3u8?team=XX&mediaType=Video&resolution=720p_alt
```

xTeVe's log has the following entry that seems to stem directly from the interaction:

```
[xTeVe] FFMPEG log: http://XXX/stream.m3u8?team=XX&mediaType=Video&resolution=720p_alt: Invalid data found when processing input
```

Any thoughts? I've made sure to have xTeVe up to date.

**Comment by tonywagner** [comment]
Probably something I messed up! I just pushed a new version, should work now. (Note those stream URLs won't play anything if a game isn't live.)

**Comment by ahughes03** [comment]
Cool- I've updated and will check things out in a couple of days. Thanks!

**Comment by ahughes03** [comment]
Thanks for the update- it seems like the streams have been working well the past few days.

Much appreciated!
