### ISSUE TITLE
Possible timezone bug in XML generation

### ISSUE THREAD

**Issue by greigm** [tonywagner/mlbserver#33]
I'm using the xml generated by the "All" option for the XMLTV guide for Jellyfin.
I'm running Jellyfin and mlbserver in two different docker containers.
I'm in New Zealand, and the TZ environment variable is set to Pacific/Auckland for both containers.

Jellyfin shows all the games as if they were in UTC instead of my local timezone.

I believe the issue is in the xml itself. For example, https://wiki.xmltv.org/index.php/XMLTVFormat shows either + OR - for the timezone offset, but here's an example entry from the mlbserver generated xml:

```
<programme channel="MLBTV.CHC" start="20240517114000 +-1200" stop="20240517144000 +-1200">
<title lang="en">MLB Baseball: Pirates at Cubs (MARQ)</title>
<desc lang="en">Jared Jones vs. Justin Steele.</desc>
<category lang="en">Sports</category>
<icon src="https://img.mlbstatic.com/mlb-photos/image/upload/ar_167:215,c_crop/fl_relative,l_team:112:fill:spot.png,w_1.0,h_1,x_0.5,y_0,fl_no_overflow,e_distort:100p:0:200p:0:200p:100p:0:100p/fl_relative,l_team:134:logo:spot:current,w_0.38,x_-0.25,y_-0.16/fl_relative,l_team:112:logo:spot:current,w_0.38,x_0.25,y_0.16/w_750/team/134/fill/spot.png"/>
</programme>
```

Note the offset is provided as +-1200.

**Comment by greigm** [comment]
I am pulling via docker-compose, so I can modify and test inline. If it works, should I fork and create a pull request, or is this something you're planning to roll in to the code to fix the bug? Happy to do whatever! 😁

**Comment by tonywagner** [comment]
Thanks, everyone! Fixed in https://github.com/tonywagner/mlbserver/commit/fb9067c1ddb076045619b4bc170197183fe53b3a
