### ISSUE TITLE
clear multiview error : Callback must be a function

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#4]
Me again- looks like the addition of multiview is giving my instance a hard time. Here's the log, it's only 3 lines before the service stops:

```
7/20/2021, 5:21:05 PM mlbserver started at http://10.0.0.11:9999
7/20/2021, 5:21:05 PM multiview server started at http://10.0.0.11:10000/multiview/master.m3u8
7/20/2021, 5:21:05 PM clear multiview error : Callback must be a function
```

I'm on npm v.7.20.0 if that helps. I removed and re-installed, and here's the npm log from installation:

```
sudo npm install -g mlbserver

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by ahughes03** [comment]
Update: Rolling back to version 2021.7.14 at least allowed me to get mlbserver up and running, but now I'm getting this error when I try to view a stream. Again, this is all happening in Plex via xTeVe, so I'm not sure if this has anything to do with your code (at least this most recent error):

```
node[240341]: 7/20/2021, 5:40:38 PM getMediaId error : Cannot read property 'team' of undefined
```

Thanks!

**Comment by tonywagner** [comment]
Sounds like you are running an older version of Node (not npm). Apparently the option I was using to delete multiview files requires Node 12.10 or greater:

https://stackoverflow.com/a/65932490

When I get a chance, I will try a different method of deleting those files.

**Comment by ahughes03** [comment]
yeah, I'm on 10.19.0- I'll update, and then switch back to the 2021.7.19 train... thanks for the heads up

**Comment by ahughes03** [comment]
updated to Node 14.17.3 and mlbserver 2021.7.19 and it's all working. Thanks for figuring out the Node issue- I wouldn't have thought to check!
