### ISSUE TITLE
mlb games no longer authenticate or play

### ISSUE THREAD

**Issue by tonywagner** [tonywagner/mlbserver#44]
As foreshadowed a few weeks ago in https://github.com/tonywagner/mlbserver/issues/42, mlb games no longer authenticate or play in the old API used by mlbserver. (milb games and Big Inning should still work.)

A new project, using a new API and combining features from both Kodi and mlbserver, is now available in a pre-alpha state here: https://github.com/tonywagner/plugin.video.mlbserver

mlb games play in that new project, including radio streams, and more features will be forthcoming.

**Comment by SethL** [comment]
Hi Tony,

Do you hope to generate a docker container in the future that incorporates the new api?  My setup is I pull the m3u from mlbserver, I dont use Kodi.

Thanks for all you do!

**Comment by tonywagner** [comment]
> Do you hope to generate a docker container in the future that incorporates the new api?

Yup! Just pushed a Docker image here: https://hub.docker.com/r/tonywagner/plugin.video.mlb

No M3U/XML support quite yet, but it's near the top of the to-do list.

**Comment by SethL** [comment]
You rock! Hey one other question, will the radio feeds ever be able to be
selected for the main audio stream? I use channels dvr and it can only play
the main audio stream.

**Comment by tonywagner** [comment]
> will the radio feeds ever be able to be selected for the main audio stream? I use channels dvr and it can only play the main audio stream.

To achieve that in Channels DVR would require running each video segment through ffmpeg, stripping the TV audio, putting the radio audio in its place, and passing along the resulting output to Channels DVR.

I'll have to learn what ffmpeg tools are available in Python, but it seems like it should be do-able.

**Comment by SethL** [comment]
Man that would be awesome!
Also with docker im assuming that the same environment variables are used
as mlbserver? Like user/pass etc?

**Comment by tonywagner** [comment]
> Also with docker im assuming that the same environment variables are used as mlbserver? Like user/pass etc?

It's simpler, so far. You can simply create a generic container and then add your credentials through the resulting web interface.

**Comment by SethL** [comment]
Gotcha. I tried that and without signing in I get a list of the games. when i signin I get page cannot be displayed. when i check the settings.xml i see my user/pass.  Then I try and look at the games and the page doesnt show any.  
in the logs I see failed to get answer 'id'

Also is the m3u path the same as it was for mlbserver? (ip:5574/channels.m3u?mediaType=Video&resolution=best)

**Comment by tonywagner** [comment]
> Gotcha. I tried that and without signing in I get a list of the games. when i signin I get page cannot be displayed. when i check the settings.xml i see my user/pass. Then I try and look at the games and the page doesnt show any.
> in the logs I see failed to get answer 'id'

Could you open this as an issue in the new repo? https://github.com/tonywagner/plugin.video.mlb

**Comment by Yankees4life** [comment]
Nice to see that m3u support is coming to the new(er) tool. It makes (re)integrating MLB.TV to Channels easier

**Comment by tonywagner** [comment]
I changed my mind and updated this program for the new API.

Let me know if anything is still broken!

**Comment by jtut1731** [comment]
Thanks @tonywagner for the mlbservers! Do you plan to keep this as the Channels DVR solution and the plugin.video.mlb as the Kodi solution? I will be testing this new update.

**Comment by charliebird** [comment]
Hey @tonywagner 
Thanks for updating mlbserver!!
I get a "
failed to getDeviceId
missing deviceId
"
crash whenever I try to play a game

**Comment by tonywagner** [comment]
> I get a "
> failed to getDeviceId
> missing deviceId
> "
> crash whenever I try to play a game

Should be fixed in https://github.com/tonywagner/mlbserver/commit/93074ce6d9ae3f47439d79643de3f89823353d3e (version 2024.07.25-3)

**Comment by tonywagner** [comment]
> Thanks @tonywagner for the mlbservers! Do you plan to keep this as the Channels DVR solution and the plugin.video.mlb as the Kodi solution? I will be testing this new update.

The original mlbserver will be more stable for a DVR solution right now.

The eventual goal would be to replace the original mlbserver with plugin.video.mlbserver -- but the latter has a long ways to go to catch up!
