### ISSUE TITLE
gamechanger m3u

### ISSUE THREAD

**Issue by warrentc3** [tonywagner/mlbserver#46]
When pulling m3u and i'm after gamechanger, but include any other "Team", gamechanger is not returned in the m3u response.

For example, this returns just the big inning channel, omitting gamechanger.
```channels.m3u?mediaType=Video&resolution=best&includeTeams=biginning,gamechanger```

If this is expected behavior and I need to obtain the gamechanger m3u via another means, that's fine.

**Comment by tonywagner** [comment]
I suspect there could be an issue with calculating the first/last games each day to determine the game changer hours. Let me know if it happens again.
