### ISSUE TITLE
sunday roku games

### ISSUE THREAD

**Issue by warrentc3** [tonywagner/mlbserver#51]
on mlbserver, it has them as national "blacked out".
however, via mlb.tv I can watch the roku games in the mlb apps on both ios and android.

i'm not sure they should quantify as "blacked out"

**Comment by tonywagner** [comment]
I was just working on that! Should be fixed in https://github.com/tonywagner/mlbserver/commit/1c4acf59a45fc345b0d51ed709e8ed3ff0ddb190
