### ISSUE TITLE
Issue with mlbserver - timeout waiting for response headers

### ISSUE THREAD

**Issue by SethL** [tonywagner/mlbserver#52]
[logs.txt](https://github.com/user-attachments/files/16701010/logs.txt)
Looks like there is an issue with mlbserver.  When I try to play any game I get a timeout waiting for response headers.   The container dies after that.  Same thing is happening with plugin.video.mlbserver so I'm thinking mlb may have changed something? Logs attached

**Comment by tonywagner** [comment]
No issues for me in either program. Be sure to clear your session/cache if you want to try again. Are you using a VPN?

**Comment by SethL** [comment]
for mlb server the issue was on my end.  a fat finger in the portainer stacks file
