### ISSUE TITLE
getStreamURL streamURL not found

### ISSUE THREAD

**Issue by charliebird** [tonywagner/mlbserver#53]
Since today, I'm getting this error on every link I try from mlbserver.
getStreamURL streamURL not found

Looks like it's all broken again :(

**Comment by tonywagner** [comment]
Works fine for me. Are you using the latest version, and have you tried clearing your session and cache? Are you using any kind of a VPN?

**Comment by charliebird** [comment]
Hi Tony, thanks for the quick reply. 
I don't think I was on the latest, so I reinstalled and cleared data and it now works. Thanks!
