### ISSUE TITLE
Issue with a National broadcast

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#6]
Hey there- again, thanks for all your work on this project, it's absolutely my go-to!

I wanted to watch the nationally broadcast game (again, via my xTeve tuner set to monitor my mlbserver instance), and got the following error:

```
Aug 07 20:06:53 mlbserver[833006]: 8/7/2021, 8:06:53 PM stream.m3u8 request : /stream.m3u8?team=NATIONAL.1&mediaType=Video&resolution=720p60
Aug 07 20:06:53 mlbserver[833006]: 8/7/2021, 8:06:53 PM getMediaId error : Cannot read property 'team' of undefined
Aug 07 20:06:53 mlbserver[833006]: 8/7/2021, 8:06:53 PM no matching game found /stream.m3u8?team=NATIONAL.1&mediaType=Video&resolution=720p60
Aug 07 20:06:53 mlbserver[833006]: 8/7/2021, 8:06:53 PM failed to get mediaId : /stream.m3u8?team=NATIONAL.1&mediaType=Video&resolution=720p60
```

I can load the stream directly from the mlbserver web interface, so I'm sure it's a communication error between xTeVe and mlbserver. I was wondering if you have any ideas?

Here's the one-liner from the xTeVe log:

```
2021-08-07 20:06:53 [xTeVe] FFMPEG log:  http://x.x.x.x:9999/stream.m3u8?team=NATIONAL.1&mediaType=Video&resolution=720p60: Invalid data found when processing input
```

Again, thanks for all you've put into this!

EDIT: Looks like it's not just the national broadcast- there was one other game on when I encountered this error and got the same message regarding not being able to read the property 'team' of undefined. I'm up on 2021.8.6 as well.

**Comment by tonywagner** [comment]
Fixed -- it was looking for a space in the national channel ID in one spot, when it should have been looking for a period ("NATIONAL.1").

If you've got a log entry for the non-national error, let me know and I could look into that too.

**Comment by ahughes03** [comment]
Here's the error for that other game:

```
Aug 07 20:33:04 mlbserver[2410609]: 8/7/2021, 8:33:04 PM stream.m3u8 request : /stream.m3u8?team=LAA&mediaType=Video&resolution=720p60
Aug 07 20:33:05 mlbserver[2410609]: 8/7/2021, 8:33:05 PM getMediaId error : Cannot read property 'team' of undefined
Aug 07 20:33:05 mlbserver[2410609]: 8/7/2021, 8:33:05 PM no matching game found /stream.m3u8?team=LAA&mediaType=Video&resolution=720p60
Aug 07 20:33:05 mlbserver[2410609]: 8/7/2021, 8:33:05 PM failed to get mediaId : /stream.m3u8?team=LAA&mediaType=Video&resolution=720p60
```

**Comment by tonywagner** [comment]
Actually the LAA stream yesterday was an error in the code too -- it was tripping up on the national game listing right before it. I pushed another fix to resolve that issue.
