### ISSUE TITLE
Big Inning

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#7]
Hey there- I was curious to check out the Big Inning feature, and it doesn't seem to be working. Any thoughts? I'm up-to-date (2021.8.24.2)...

First two lines are from a fresh instance of the app. I then tried it via xTeVe, and then via the webui, first as an embedded feed, and then as a stream. None of those options were able to successfully play the stream.

Thanks for looking into it.

EDIT: Quick note, all other streams are working just fine, so I'm guessing it's how the stream is being called?

```
Aug 26 17:32:10 mlbserver[2197112]: 8/26/2021, 5:32:10 PM mlbserver started at http://10.0.0.11:9999
Aug 26 17:32:10 mlbserver[2197112]: 8/26/2021, 5:32:10 PM multiview server started at http://10.0.0.11:10000/multiview/master.m3u8
Aug 26 17:34:38 mlbserver[2197112]: 8/26/2021, 5:34:38 PM stream.m3u8 request : /stream.m3u8?type=biginning&mediaType=Video&resolution=720p60
Aug 26 17:34:40 mlbserver[2197112]: 8/26/2021, 5:34:40 PM failed to get streamURL : /stream.m3u8?type=biginning&mediaType=Video&resolution=720p60
Aug 26 17:35:35 mlbserver[2197112]: 8/26/2021, 5:35:35 PM embed.html request : /embed.html?type=biginning
Aug 26 17:35:37 mlbserver[2197112]: 8/26/2021, 5:35:37 PM stream.m3u8 request : /stream.m3u8?type=biginning
Aug 26 17:35:39 mlbserver[2197112]: 8/26/2021, 5:35:39 PM failed to get streamURL : /stream.m3u8?type=biginning
Aug 26 17:36:47 mlbserver[2197112]: 8/26/2021, 5:36:47 PM embed.html request : /embed.html?type=biginning
Aug 26 17:36:47 mlbserver[2197112]: 8/26/2021, 5:36:47 PM stream.m3u8 request : /stream.m3u8?type=biginning
Aug 26 17:36:49 mlbserver[2197112]: 8/26/2021, 5:36:49 PM failed to get streamURL : /stream.m3u8?type=biginning
```

**Comment by tonywagner** [comment]
I suppose the log was sparse. :)

But the absence of more serious errors gave me a good clue about what was going on.

I just pushed another update which hopefully addresses the Big Inning issue, for now.
