### ISSUE TITLE
Is there a way to store/hash MLB Login credentials?

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#8]
Hey there- things have been working really smoothly for a while now! Thanks again for all the updates throughout the season, it's been great.

I was wondering if there's a way to have my MLB Login credentials stored, so that any time the session/cache is cleared, the app could pull the credentials from a file/hash? I have your program set up to run via systemd, and there have been times I have to restart the program manually to store the credentials in a cache so systemd can run without intervention.

Just a question- if it doesn't make sense, no big deal on my end!

**Comment by tonywagner** [comment]
When you input your credentials on first run, mlbserver stores them in a "credentials.json" file in the installation folder (wherever npm puts it) and retrieves them without prompting on all future runs. Only if that "credentials.json" file is deleted will mlbserver prompt for credentials again, and mlbserver itself won't delete the file unless you run the program with the "--logout" (or "-l") flag, so you can clear session/cache separately (they are stored in separate folders/files). 

At least that's how it's supposed to work. I just start it at boot with cron and I've never had to re-enter my credentials. Not sure how systemd should be any different? If you could consistently reproduce the behavior, I'd be happy to try it out in a VM.

**Comment by ahughes03** [comment]
Ok- good to know. In my instance, there have been times where the program times out on a stream request, and give the “blackout” log line. The way I’ve been clearing this is by stopping my service, and running an update (which should flush the current credentials). I’m just wondering if the program can look at an alternative file if there isn’t a credentials.json, instead of requiring user input to recreate the file. I feel like it could be called via a command option, just like the web ui user:password option you created recently. 

No problem if this isn’t something you want to look into, I’ve got a workflow that gets the job done, just looking for ways to make things a little more robust. 

Thanks!!

**Comment by ahughes03** [comment]
I'm going to close the issue, since it's not a bug, but rather a feature request that seems specific to my setup. Thanks again!

**Comment by tonywagner** [comment]
> I'm going to close the issue, since it's not a bug, but rather a feature request that seems specific to my setup. Thanks again!

Actually I thought this was a good suggestion! I just hadn't gotten around to it yet.

I've pushed a new update that lets you specify account credentials on the command line, along with various other improvements.
