### ISSUE TITLE
Error using the new additional parameters for account_username & account_password

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#9]
Hey there- love the added options for the new update. I updated to  2021.10.1, and ran `mlbserver -l` to ensure the session was logged out and any caches cleared. Then I ran mlbserver with the new parameters for `account_username` and `account_password` and got the following error.

```
10/1/2021, 10:12:35 AM reset session error : ENOENT: no such file or directory, unlink '/usr/local/lib/node_modules/mlbserver/data/cookies.json'
```

Running the same command after this error, (including the additional parameters), works just fine...

What am I missing?

**Comment by tonywagner** [comment]
I see what's happening. I told it to clear any session data when new credentials are loaded. But in this case, on the first run, no session data exists yet. And to make matters worse, I also had it halting execution on that error for some reason, which probably isn't necessary!

I just pushed another update with a fix.

**Comment by ahughes03** [comment]
Awesome- the update fixed the issue. Thanks for all the work on this!!

**Comment by tonywagner** [comment]
> Awesome- the update fixed the issue. Thanks for all the work on this!!

FYI, I just had to push an additional fix -- my new content protection code was causing it to erroneously load the sample stream for a bunch of requests. So you'll want to pull down the latest version again.

**Comment by ahughes03** [comment]
Thanks for the heads up. Updated to 2021.10.02 without issue.
